site_name: SANS Holiday Hack Challenge 2024 Write-up
site_url: https://tominthebytes.github.io/SANS-HHC-2024/
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: custom
    accent: custom
  icon:
    logo: fontawesome/solid/terminal
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.instant
    - navigation.path
    - navigation.sections
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tooltips
plugins:
  - search
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - admonition
  - attr_list
  - footnotes
  - def_list
  - tables
nav:
  - Welcome: index.md
  - Prologue:
      - Holiday Hack Orientation: prologue/holiday_hack_orientation.md
      - Elf Connect: prologue/elf_connect.md
      - Elf Minder 9000: prologue/elf_minder_9000.md
  - Act 1:
      - Frosty Keypad: act_1/frosty_keypad.md
      - cURLing: act_1/cURLing.md
      - Hardware Hacking 101: act_1/hardware_hacking_101.md
  - Act 2:
      - Mobile Analysis: act_2/mobile_analysis.md
      - Drone Path: act_2/drone_path.md
      - PowerShell: act_2/powershell.md
      - Snowball Showdown: act_2/snowball_showdown.md
      - Microsoft KC7: act_2/microsoft_kc7.md
  - Act 3:
      - Santa Vision: act_3/santa_vision.md
      - Elf Stack: act_3/elf_stack.md
      - Decrypt the Naughty-Nice List: act_3/decrypt.md
      - Deactivate Frostbit Naughty-Nice List Publication: act_3/deactivate.md
